#!/bin/bash


# Use synapse as our app launcher. (-s: don't display until requested) 
if [ -z "$(pgrep synapse)" ] ; then
  synapse -s &
fi

if [ -z "$(pgrep trayer)" ] ; then
  trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand false --width 52 --widthtype pixel --transparent true --tint 0x222222 --alpha 0 --height 24 &
fi

#xrdb -merge ~/.Xresources &

#nm-applet &

#gnome-sound-applet &

if [ -z "$(pgrep firefox)" ] ; then
  firefox &
fi

#skype &

#if [ -z "$(pgrep keepass2)" ] ; then
#  keepass2 &
#fi

